#!/bin/bash

export BERT_BASE_DIR=/data/bert/cased_L-12_H-768_A-12
#export BERT_BASE_DIR=/data/bert/uncased_L-12_H-768_A-12
#export BERT_BASE_DIR=/data/bert/uncased_L-24_H-1024_A-16
#export GLUE_DIR=/data/glue/glue_data
export MCQA_DIR=/data/ARCQC/tiny/
export BERT_OUTPUT_DIR=/data/bert_out/

rm -r $BERT_OUTPUT_DIR
mkdir $BERT_OUTPUT_DIR
mkdir $BERT_OUTPUT_DIR/dev
mkdir $BERT_OUTPUT_DIR/test

python run_classifier2.py \
  --task_name=MCQA \
  --do_train=true \
  --do_eval=true \
  --do_lower_case=False \
  --data_dir=$MCQA_DIR \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=8 \
  --learning_rate=2e-5 \
  --num_train_epochs=1.0 \
  --output_dir=$BERT_OUTPUT_DIR

python run_classifier2.py \
  --task_name=MCQA \
  --do_predict=true \
  --data_dir=$MCQA_DIR \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_OUTPUT_DIR \
  --max_seq_length=128 \
  --output_dir=$BERT_OUTPUT_DIR/test
