#!/bin/bash

export BERT_BASE_DIR=/data/bert/cased_L-12_H-768_A-12
#export BERT_BASE_DIR=/data/bert/uncased_L-12_H-768_A-12
#export BERT_BASE_DIR=/data/bert/uncased_L-24_H-1024_A-16
export GLUE_DIR=/data/glue/glue_data
export BERT_OUTPUT_DIR=/data/bert_out/


python run_classifier.py \
  --task_name=MRPC \
  --do_train=true \
  --do_eval=true \
  --do_lower_case=False \
  --data_dir=$GLUE_DIR/MRPC \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=32 \
  --learning_rate=2e-5 \
  --num_train_epochs=3.0 \
  --output_dir=$BERT_OUTPUT_DIR

python run_classifier.py \
  --task_name=MRPC \
  --do_predict=true \
  --data_dir=$GLUE_DIR/MRPC \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_OUTPUT_DIR \
  --max_seq_length=128 \
  --output_dir=$BERT_OUTPUT_DIR
